services:
  komodo:
    image: ghcr.io/moghtech/komodo-core:${KOMODO_VERSION:-latest}
    container_name: komodo
    restart: unless-stopped
    networks:
      - db
      - management
    ports:
      - 9120:9120
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${MONGO_USERNAME:-mongo}
      KOMODO_DATABASE_PASSWORD: ${MONGO_PASSWORD:-mongo}
    labels:
      komodo.skip: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH:-/opt/services}/komodo/repo-cache:/repo-cache
      - ${SERVICE_PATH:-/opt/services}/komodo/syncs:/syncs

  mongo:
    image: mongo:${MONGO_VERSION:-latest}
    container_name: mongo
    restart: unless-stopped
    command: --quiet --wiredTigerCacheSizeGB 0.25
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-mongo}
    labels:
      komodo.skip: 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH:-/opt/services}/mongo/data:/data/db
      - ${SERVICE_PATH:-/opt/services}/mongo/config:/data/configdb

networks:
  db:
    external: true
  management:
    external: true